"""create events table in db

Revision ID: 604f4a7e3a2d
Revises: 87c1f14eb1bc
Create Date: 2024-02-03 13:01:49.067391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604f4a7e3a2d'
down_revision = '87c1f14eb1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('date_hosted', sa.DateTime(), nullable=False),
    sa.Column('attendees', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=20)), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
